### ISSUE TITLE
Release please? Readme documentation does not match version

### ISSUE THREAD

**Issue by siliconcat** [sksamuel/sbt-avro4s#3]
Hi,

I was trying to use the plugin, but it seems that 0.91 -the version mentioned in the documentation- is old and does not match the information in the Readme file. I cannot seem to find a newer version anywhere or snapshots?

Thanks!

**Comment by sksamuel** [comment]
The problem is avro4s is no longer shipped for scala 2.10 and sbt needs a scala 2.10 version.

**Comment by SohumB** [comment]
`sbt-avro4s` only depends on `avro4s-generator`, though, which compiles fine under `2.10.6` afaict. Can just that package be published be as `2.10`?

**Comment by sksamuel** [comment]
Fair point.

**Comment by sksamuel** [comment]
The whole generator can probably just move in here.
